# Generated by Django 2.0.6 on 2018-06-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Search',
        ),
    ]
