# Generated by Django 2.0.6 on 2018-06-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_auto_20180621_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.TextField(max_length=512)),
                ('title_hangul', models.TextField(max_length=512)),
                ('date', models.TextField(max_length=512)),
                ('keyword', models.TextField(max_length=512)),
                ('major', models.TextField(max_length=512)),
                ('middle', models.TextField(max_length=512)),
                ('code', models.TextField(max_length=512)),
                ('imagelink', models.TextField(max_length=512)),
                ('title_hanja', models.TextField(max_length=512)),
            ],
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
